apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
    generateName: "uetest-"
spec:
    ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 7777
    health:
        disabled: false
        periodSeconds: 10
        failureThreshold: 3
        initialDelaySeconds: 60
        spec:
            containers:
                - name: UE-test
                  image: nanduansc/ag-test
